stages:
  - test
  - build
  - image
  - tag
  - bundle

.build:go: &go-job
  stage: build
  image: apextoaster/golang:master
  tags:
    - runner:k8s
    - compute:high
  variables:
    GOPATH: /build

  before_script:
    - /usr/local/go/bin/dep ensure

  artifacts:
    expire_in: 1 hour
    paths:
      - bin/
  cache: &go-cache
    paths:
      - vendor
    policy: pull

test:go:
  <<: *go-job
  stage: test
  script:
    - go test -cover ./...
  cache:
    <<: *go-cache
    policy: pull-push

build:go:darwin-x86:
  <<: *go-job
  script:
    - GOOS=darwin GOARCH=386 go build -o bin/togo-darwin-386
    - GOOS=darwin GOARCH=amd64 go build -o bin/togo-darwin-amd64

build:go:linux-arm:
  <<: *go-job
  script:
    - GOOS=linux GOARCH=arm go build -o bin/togo-linux-arm
    - GOOS=linux GOARCH=arm64 go build -o bin/togo-linux-arm64

build:go:linux-x86:
  <<: *go-job
  script:
    - GOOS=linux GOARCH=386 go build -o bin/togo-linux-386
    - GOOS=linux GOARCH=amd64 go build -o bin/togo-linux-amd64

build:go:windows-x86:
  <<: *go-job
  script:
    - GOOS=windows GOARCH=386 go build -o bin/togo-windows-386.exe
    - GOOS=windows GOARCH=amd64 go build -o bin/togo-windows-amd64.exe

# always build an image (tagged by branch), publish tags to latest
.build:docker: &build-docker
  image: docker
  services:
    - docker:dind
  tags:
    - runner:k8s
    - cloud:aws

  before_script:
    # prep secrets
    - mkdir /root/.docker
    - ln -s /secrets/docker /root/.docker/config.json
    - docker info
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    IMAGE_TAG: ssube/togo:$CI_COMMIT_REF_SLUG
 
build:image:
  <<: *build-docker
  stage: image
 
  dependencies:
    - build:go:linux-x86
  script:
    # build it
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# tag releases
tag:latest:
  <<: *build-docker
  stage: tag
  only:
    - master

  script:
    # build it
    - docker pull ssube/togo:master
    - docker tag ssube/togo:master ssube/togo:latest
    - docker push ssube/togo:latest

tag:version:
  <<: *build-docker
  stage: tag
  only:
    - tags

  script:
    # build it
    - docker pull ssube/togo:master
    - docker tag ssube/togo:master ssube/togo:${CI_COMMIT_TAG}
    - docker push ssube/togo:${CI_COMMIT_TAG}

bundle:
  image: apextoaster/base:master
  stage: bundle
  tags:
    - runner:k8s
  only:
    - master
    - tags

  dependencies:
    - build:go:darwin-x86
    - build:go:linux-arm
    - build:go:linux-x86
    - build:go:windows-x86

  script:
    - tar -cvf bin/togo_all.tgz bin/*
    - gzip bin/togo-darwin-*
    - gzip bin/togo-linux-*

  artifacts:
    expire_in: 1 day
    paths:
      - bin/