stages:
  - test
  - build
  - image
  - tag

.build:go: &go-job
  stage: build
  image: apextoaster/golang:1.14-master
  tags:
    - runner:k8s
    - compute:high
  variables:
    GOPATH: /build
    BUILD_OPTS: -a -v -x

  before_script:
    - make go-clean

  artifacts:
    expire_in: 1 hour
    paths:
      - bin/

  cache: &go-cache
    paths:
      - vendor
    policy: pull

test:go:
  <<: *go-job
  stage: test
  allow_failure: true # TODO: fix this once the tests compile
  script:
    - make go-test
  cache:
    <<: *go-cache
    policy: pull-push

build:go:darwin-x86:
  <<: *go-job
  script:
    - GOOS=darwin GOARCH=386 make go-build
    - GOOS=darwin GOARCH=amd64 make go-build

build:go:linux-arm:
  <<: *go-job
  script:
    - GOOS=linux GOARCH=arm make go-build
    - GOOS=linux GOARCH=arm64 make go-build

build:go:linux-x86:
  <<: *go-job
  script:
    - GOOS=linux GOARCH=386 make go-build
    - GOOS=linux GOARCH=amd64 make go-build

build:go:windows-x86:
  <<: *go-job
  script:
    - GOOS=windows GOARCH=386 make go-build
    - GOOS=windows GOARCH=amd64 make go-build

# always build an image (tagged by branch), publish tags to latest
.build:docker: &build-docker
  image: apextoaster/docker:18.09
  services:
    - apextoaster/docker-dind:18.09
  tags:
    - runner:k8s
    - cloud:aws

  before_script:
    # prep secrets
    - mkdir /root/.docker
    - ln -s /secrets/docker /root/.docker/config.json
    - docker info
  variables: &vars-docker
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    IMAGE_TAG: ssube/togo:$CI_COMMIT_REF_SLUG

.build.retag: &build-retag
  stage: tag
  script:
    - docker pull ${IMAGE_SRC}
    - docker tag ${IMAGE_SRC} ${IMAGE_DST}
    - docker push ${IMAGE_DST}
 
build:image:
  <<: *build-docker
  stage: image
 
  dependencies:
    - build:go:linux-x86
  script:
    # build it
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# tag releases
tag:latest:
  <<: [*build-docker, *build-retag]
  only:
    - master

  variables:
    <<: *vars-docker
    IMAGE_SRC: ssube/togo:master
    IMAGE_DST: ssube/togo:latest

tag:version:
  <<: [*build-docker, *build-retag]
  only:
    - tags

  variables:
    <<: *vars-docker
    IMAGE_SRC: ssube/togo:master
    IMAGE_DST: ssube/togo:${CI_COMMIT_TAG}

tag:bundle:
  image: apextoaster/base:1.3-master
  stage: tag
  tags:
    - runner:k8s
  only:
    - master
    - tags

  dependencies:
    - build:go:darwin-x86
    - build:go:linux-arm
    - build:go:linux-x86
    - build:go:windows-x86

  script:
    - make bundle-all

  artifacts:
    expire_in: 1 day
    paths:
      - bin/