stages:
  - build
  - image

build:go:
  stage: build
  image: andrexus/golang-dep
  tags:
    - runner:k8s
    - compute:high
  script:
    - dep ensure
    - go build
  variables:
    GOPATH: /build

  artifacts:
    expire_in: 1 hour
    paths:
      - togo
  cache:
    paths:
      - vendor

build:image:
  stage: image
  image: docker
  services:
    - docker:dind
  tags:
    - runner:k8s
    - cloud:aws
  
  dependencies:
    - build:go
  script:
    # prep secrets
    - mkdir /root/.docker
    - ln -s /secrets/docker /root/.docker/config.json
    - docker info
    # build it
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    IMAGE_TAG: ssube/togo:$CI_COMMIT_REF_SLUG
